POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Renato Portaluppi", 
   "email": "clara@react.com" ,
   "password": "12345678",
   "role": "NORMAL"
}

###

GET http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "cesar@gauchismo.com" ,
   "password": "123456"
}